databaseChangeLog:
    - changeSet:
        id: initial-users
        author: igor

        changes:
            - createTable:
                tableName: users
                columns:
                    - column: &primaryKeyColumn
                        name: id
                        type: bigint
                        autoIncrement: true
                        constraints:
                            primaryKey: true
                    - column:
                        name: name
                        type: nvarchar(255)

            - loadData:
                tableName: users
                file: config/liquibase/initial/data/users.csv
                separator: ;
